version: "2.3"
services:
  nvim:
    build:
      context: .
      dockerfile: nvim/Dockerfile
      args:
        BASE_IMAGE: "ubuntu:20.04"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USERNAME: ${USERNAME}
    image: "hsc-wp:nvim"
    # command: ["jupyter", "lab", "--allow-root", "--port=8888", "--ip=0.0.0.0"]
    container_name: "hsc-wp-nvim"
    volumes:
      - ${HOME}:/environment
    working_dir: "/environment"
    shm_size: '32gb'
    ports:
      - "4569:8888"
    tty: true
    stdin_open: true

    env_file:
      - .env
  jupyterlab-cuda:
    build:
      context: .
      dockerfile: jupyterlab_cuda/Dockerfile
      args:
        BASE_IMAGE: "nvidia/cuda:11.2.0-cudnn8-runtime-ubuntu20.04"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USERNAME: ${USERNAME}
        REQUIREMENTS_FILE: "jupyterlab_cuda/requirements.txt"
    image: "hsc-wp:jupyterlab-cuda"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # command: ["jupyter", "lab", "--allow-root", "--port=8888", "--ip=0.0.0.0"]
    container_name: "hsc-wp-jupyterlab-cuda"
    volumes:
      - ${HOME}:/environment
    working_dir: "/environment"
    shm_size: '32gb'
    ports:
      - "4569:8888"
    tty: true
    stdin_open: true

    env_file:
      - .env
  jupyter-lab:
    build:
      context: .
      dockerfile: jupyterlab/Dockerfile
      args:
        BASE_IMAGE: "ubuntu:20.04"
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        USERNAME: ${USERNAME}
    image: "hsc-wp:jupyterlab"
    # command: ["jupyter", "lab", "--allow-root", "--port=8888", "--ip=0.0.0.0"]
    container_name: "hsc-wp-jupyterlab"
    volumes:
      - ${HOME}:/environment
    working_dir: "/environment"
    shm_size: '32gb'
    ports:
      - "4569:8888"
    tty: true
    stdin_open: true
    env_file:
      - .env
